#!/bin/sh
module="xwaya"
device="xwaya"
mode="600"

/sbin/insmod ./$module.ko $* || exit 1
#/sbin/insmod ./$module.ko $1 || exit 1

rm -f /dev/${device}

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

mknod /dev/${device} c $major 0

chgrp root /dev/${device}
chmod $mode /dev/${device}
